### ISSUE TITLE
Is there any particular reason this package can't support earlier OS's?

### ISSUE THREAD

**Issue by edonv** [dagronf/Bookmark#1]
I see the noted minimum required OS versions for the package, and it seemed odd. I just downloaded the repo, lowered the platform versions, and commented-out the `@available(macOS 10.12, iOS 14, tvOS 14, *)` on the class, and it builds fine. Was there a particular reason to lock it to the noted OS versions?

**Comment by dagronf** [comment]
The short version is - I can't remember :-)  It may have been an issue a couple of years back with Xcode, but it doesn't seem to be an issue for modern Xcode.

I've merged your change in as v3.0.0 just in case there's an issue that I'm unaware of (so that projects don't automatically upgrade to it.)

Thanks for your work!
